### PR TITLE
docs: add use with jest

### PR DESCRIPTION
**Pull request by balibebas**

### CODE REVIEW

**Comment by balibebas** [comment]
Closing due to age.

**Comment by filhodoto** [comment]
This is helpful information and still up to date at the time of this comment, any reason why it has not been merged?
Cheers @balibebas

**Comment by mongkuen** [comment]
Made a note about it, thanks for bringing this to my attention

**Comment by balibebas** [comment]
lmk if there's anything I can do to help. thanks for the updates

**Pull request closed without merging**
